---
ah_auto_approve: true
ah_collections:
  - collection_name: test
    git_url: https://github.com/sean-m-sullivan/collection_test.git
    # key_path: "{{ lookup('env', 'MY_CERT_FILE') }}"
    # ssh_opts: '-o StrictHostKeyChecking=no'
...
