---
ah_namespaces:
  - name: community_test
    company: Ansible by Red Hat
    email: ddaniels@redhat.com
    avatar_url: https://static.redhat.com/libs/redhat/brand-assets/latest/corp/logo.svg
    description: Namespace to test publishing collections
    resources: "# Redhat CoP\nA Namespace to test publishing collections"
    links:
      - name: "Red Hat"
        url: "https://www.redhat.com"
...
