---
# ee_base_image: registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8
# ee_builder_image: registry.redhat.io/ansible-automation-platform-22/ansible-builder-rhel8
ee_image_push: true
ee_validate_certs: false
ee_create_ansible_config: false
# ee_auth_file:
# ee_executable:
# ee_ca_cert_dir:
# ee_sign_by:
...
