---
controller_credentials_all:
  - name: aap_admin
    credential_type: Red Hat Ansible Automation Platform
    organization: config_as_code
    description: aap admin account
    inputs:
      host: "{{ aap_hostname }}"
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      verify_ssl: false

  - name: hub_admin_user_pass
    credential_type: automation_hub
    organization: config_as_code
    description: automation hub admin account
    inputs:
      hostname: "{{ aap_hostname }}"
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      verify_ssl: false

  - name: hub_token_user
    credential_type: automation_hub
    organization: config_as_code
    description: automation hub api account
    inputs:
      hostname: "{{ aap_hostname }}"
      username: "{{ hub_token_username }}"
      token: "{{ hub_token }}"
      verify_ssl: false

  - name: hub_certified
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: config_as_code
    inputs:
      url: https://{{ aap_hostname }}/pulp_ansible/galaxy/rh-certified/
      token: "{{ hub_token }}"

  - name: hub_published
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: config_as_code
    inputs:
      url: https://{{ aap_hostname }}/pulp_ansible/galaxy/published/
      token: "{{ hub_token }}"

  - name: hub_validated
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: config_as_code
    inputs:
      url: https://{{ aap_hostname }}/pulp_ansible/galaxy/validated/
      token: "{{ hub_token }}"

  - name: hub_community
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: config_as_code
    inputs:
      url: https://{{ aap_hostname }}/pulp_ansible/galaxy/community/
      token: "{{ hub_token }}"

  - name: cr_ah
    credential_type: Container Registry
    organization: config_as_code
    inputs:
      host: "{{ aap_hostname }}"
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      verify_ssl: false

  - name: root
    credential_type: Machine
    organization: config_as_code
    description: root local password
    inputs:
      username: root
      password: "{{ root_machine_pass }}"

  - name: vault
    credential_type: Vault
    organization: config_as_code
    description: vault password
    inputs:
      vault_password: "{{ vault_pass }}"

# here is an example for getting git ssh cred working
# - name: github
#   credential_type: Source Control
#   organization: config_as_code
#   description: github
#   inputs:
#     username: ""
#     ssh_key_data: "{{ ssh_priv_key }}"
#     ssh_key_unlock: "{{ ssh_key_unlock }}"
...
