---
hub_token_username: token_user
aap_user_accounts_all:
  - username: api_user
    is_superuser: false
    password: "{{ controller_api_user_pass }}"
  - username: token_user
    # Currently not working
    # groups:
    #   - "admin"
    append: true
    is_superuser: true
    password: "{{ hub_api_user_pass }}"
    state: present
...
