---
controller_templates_all:
  - name: controller_config
    project: config_as_code
    job_type: run
    playbook: playbooks/controller_config.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    ask_variables_on_launch: true
    limit: "{{ env }}"
    verbosity: 0
    credentials:
      - aap_admin
      - ah_token_user
      - vault
    extra_vars:
      # for debugging errors with creds change to false
      controller_configuration_credentials_secure_logging: true

  - name: ah_config
    project: config_as_code
    job_type: run
    playbook: playbooks/hub_config.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    limit: "{{ env }}"
    verbosity: 0
    credentials:
      - ah_token_user
      - vault

  - name: build_execution_environments
    project: config_as_code
    job_type: run
    playbook: playbooks/build_ee.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    verbosity: 0
    credentials:
      - root
      - ah_admin_user_pass
    labels:
      - EE

  - name: build_custom_collections
    project: config_as_code
    job_type: run
    playbook: playbooks/custom_collection.yml
    inventory: config_as_code
    execution_environment: supported
    concurrent_jobs_enabled: false
    limit: "{{ env }}"
    verbosity: 0
    credentials:
      - root
      - ah_token_user

  - name: console_token_refresh
    project: config_as_code
    job_type: run
    playbook: playbooks/console_token_refresh.yml
    inventory: config_as_code
    execution_environment: minimal
    concurrent_jobs_enabled: false
    limit: "{{ env }}"
    verbosity: 0
    credentials:
      - vault
...
