---
controller_applications: "{{ controller_applications_all + controller_applications_prod }}"
controller_credential_input_sources: "{{ controller_credential_input_sources_all + controller_credential_input_sources_prod }}"
controller_credential_types: "{{ controller_credential_types_all + controller_credential_types_prod }}"
controller_credentials: "{{ controller_credentials_all + controller_credentials_prod }}"
controller_execution_environments: "{{ controller_execution_environments_all + controller_execution_environments_prod }}"
controller_groups: "{{ controller_groups_all + controller_groups_prod }}"
controller_hosts: "{{ controller_hosts_all + controller_hosts_prod }}"
controller_instance_groups: "{{ controller_instance_groups_all + controller_instance_groups_prod }}"
controller_inventories: "{{ controller_inventories_all + controller_inventories_prod }}"
controller_inventory_sources: "{{ controller_inventory_sources_all + controller_inventory_sources_prod }}"
controller_templates: "{{ controller_templates_all + controller_templates_prod }}"
controller_labels: "{{ controller_labels_all + controller_labels_prod }}"
controller_notifications: "{{ controller_notifications_all + controller_notifications_prod }}"
controller_organizations: "{{ controller_organizations_all + controller_organizations_prod }}"
controller_projects: "{{ controller_projects_all + controller_projects_prod }}"
controller_roles: "{{ controller_roles_all + controller_roles_prod }}"
controller_schedules: "{{ controller_schedules_all + controller_schedules_prod }}"
controller_settings: "{{ controller_settings_all | combine(controller_settings_prod, list_merge='append', recursive=true) }}"
controller_teams: "{{ controller_teams_all + controller_teams_prod }}"
controller_user_accounts: "{{ controller_user_accounts_all + controller_user_accounts_prod }}"
controller_workflows: "{{ controller_workflows_all + controller_workflows_prod }}"
env: prod
scm_branch: "" # when you want it to be default branch just set to ""
...
