---
controller_inventory_sources_dev:
  - name: controller_config_source_dev
    organization: config_as_code
    source: scm
    source_project: config_as_code_dev
    source_path: inventory_{{ env }}.yml
    inventory: config_as_code_dev
    credential: ""
    overwrite: true
    overwrite_vars: true
    update_cache_timeout: 0
...
