---
controller_applications: "{{ controller_applications_all + controller_applications_dev }}"
controller_credential_input_sources: "{{ controller_credential_input_sources_all + controller_credential_input_sources_dev }}"
controller_credential_types: "{{ controller_credential_types_all + controller_credential_types_dev }}"
controller_credentials: "{{ controller_credentials_all + controller_credentials_dev }}"
controller_execution_environments: "{{ controller_execution_environments_all + controller_execution_environments_dev }}"
controller_groups: "{{ controller_groups_all + controller_groups_dev }}"
controller_hosts: "{{ controller_hosts_all + controller_hosts_dev }}"
controller_instance_groups: "{{ controller_instance_groups_all + controller_instance_groups_dev }}"
controller_inventories: "{{ controller_inventories_all + controller_inventories_dev }}"
controller_inventory_sources: "{{ controller_inventory_sources_all + controller_inventory_sources_dev }}"
controller_templates: "{{ controller_templates_all + controller_templates_dev }}"
controller_labels: "{{ controller_labels_all + controller_labels_dev }}"
controller_notifications: "{{ controller_notifications_all + controller_notifications_dev }}"
controller_organizations: "{{ controller_organizations_all + controller_organizations_dev }}"
controller_projects: "{{ controller_projects_all + controller_projects_dev }}"
controller_roles: "{{ controller_roles_all + controller_roles_dev }}"
controller_schedules: "{{ controller_schedules_all + controller_schedules_dev }}"
controller_settings: "{{ controller_settings_all | combine(controller_settings_dev, list_merge='append') }}"
controller_teams: "{{ controller_teams_all + controller_teams_dev }}"
controller_user_accounts: "{{ controller_user_accounts_all + controller_user_accounts_dev }}"
controller_workflows: "{{ controller_workflows_all + controller_workflows_dev }}"
env: dev
scm_branch: "" # when you want it to be default branch just set to ""
...
