---
- name: Configure private automation hub after installation
  hosts: all
  gather_facts: false
  connection: local
  vars_files:
    - ../vaults/{{ env }}.yml
  tasks:
    - name: Include collection_remote role
      ansible.builtin.include_role:
        name: infra.ah_configuration.collection_remote

    - name: Include collection_repository role
      ansible.builtin.include_role:
        name: infra.ah_configuration.collection_repository

    - name: Include collection_repository_sync role
      ansible.builtin.include_role:
        name: infra.ah_configuration.collection_repository_sync

    - name: Publish custom collections
      when: publish | default(false)
      block:
        - name: Include namespace role
          ansible.builtin.include_role:
            name: infra.ah_configuration.namespace

        - name: Include publish role
          ansible.builtin.include_role:
            name: infra.ah_configuration.publish

    - name: Include ee_registry role
      ansible.builtin.include_role:
        name: infra.ah_configuration.ee_registry
      when: ah_ee_registries | length is not match('0')

    - name: Include ee_registry_index role
      ansible.builtin.include_role:
        name: infra.ah_configuration.ee_registry_index
      when: ah_ee_registries | length is not match('0')

    - name: Include ee_registry_sync role
      ansible.builtin.include_role:
        name: infra.ah_configuration.ee_registry_sync
      when: ah_ee_registries | length is not match('0')

    - name: Include ee_repository role
      ansible.builtin.include_role:
        name: infra.ah_configuration.ee_repository
      when: ah_ee_repositories | length is not match('0')

    - name: Include ee_repository_sync role
      ansible.builtin.include_role:
        name: infra.ah_configuration.ee_repository_sync
      when: ah_ee_repositories | length is not match('0')

    - name: Include ee_image role
      ansible.builtin.include_role:
        name: infra.ah_configuration.ee_image
      when: ah_ee_images | length is not match('0')

    - name: Include group role
      ansible.builtin.include_role:
        name: infra.ah_configuration.group
      when: ah_groups | length is not match('0')

    - name: Include group_roles role
      ansible.builtin.include_role:
        name: infra.ah_configuration.group_roles
      when: ah_group_roles | length is not match('0')

    - name: Include user role
      ansible.builtin.include_role:
        name: infra.ah_configuration.user
      when: ah_users | length is not match('0')
...
